export const GET_PRODUCT = "GET_PRODUCT";
export const GET_PRODUCT_BY_ID = "GET_PRODUCT_BY_ID";
export const POST_PRODUCT = "POST_PRODUCT";
export const EDIT_PRODUCT_BY_ID = "EDIT_PRODUCT_BY_ID";
export const DELETE_PPRODUCT_BY_ID = "DELETE_PPRODUCT_BY_ID";
